language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

sudo: required

services:
  - docker

branches:
  only:
    - master

script:
  - docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
  - dotnet restore ./Jet.Service.Manifest.UnitTest.Client/Jet.Service.Manifest.UnitTest.Client.csproj
  - dotnet build ./Jet.Service.Manifest.UnitTest.Client/Jet.Service.Manifest.UnitTest.Client.csproj
  - dotnet test ./Jet.Service.Manifest.UnitTest.Client/Jet.Service.Manifest.UnitTest.Client.csproj
